use dir_writer::{FileCollector, GeneratorArgs, IntermediateRepr, LanguageFeatures};

mod functions;
mod generated_types;
mod ir_to_gleam;
mod package;
mod r#type;
mod utils;

#[derive(Default)]
pub struct GleamLanguageFeatures;

impl LanguageFeatures for GleamLanguageFeatures {
    const CONTENT_PREFIX: &'static str = r#"
//// ----------------------------------------------------------------------------
////
////  Welcome to Baml! To use this generated code, please run the following:
////
////  $ gleam add baml_gleam
////
//// ----------------------------------------------------------------------------
////
//// This file was generated by BAML: please do not edit it. Instead, edit the
//// BAML files and re-generate this code using: baml-cli generate
//// baml-cli is available with the baml package.
    "#;

    fn name() -> &'static str {
        "gleam"
    }

    fn generate_sdk_files(
        &self,
        collector: &mut FileCollector<Self>,
        ir: std::sync::Arc<IntermediateRepr>,
        _args: &GeneratorArgs,
    ) -> Result<(), anyhow::Error> {
        let pkg = package::CurrentRenderPackage::new("baml_client", ir.clone());
        
        // Generate core files
        collector.add_file("src/baml_client.gleam", functions::render_client(&pkg)?)?;
        collector.add_file("src/baml_types.gleam", generated_types::render_types(&pkg)?)?;
        collector.add_file("src/baml_runtime.gleam", functions::render_runtime(&pkg)?)?;
        collector.add_file("src/baml_ffi.gleam", functions::render_ffi(&pkg)?)?;
        
        Ok(())
    }
}

#[cfg(test)]
mod gleam_tests {
    use test_harness::{create_code_gen_test_suites, TestLanguageFeatures};

    impl TestLanguageFeatures for crate::GleamLanguageFeatures {
        fn test_name() -> &'static str {
            "gleam"
        }
    }

    create_code_gen_test_suites!(crate::GleamLanguageFeatures);
}

#[cfg(test)]
mod tests {
    #[test]
    fn test_name() {
        use std::str::FromStr;

        use dir_writer::LanguageFeatures;

        let gen_type = baml_types::GeneratorOutputType::from_str(crate::GleamLanguageFeatures::name())
            .expect("GleamLanguageFeatures name should be a valid GeneratorOutputType");
        assert_eq!(gen_type, baml_types::GeneratorOutputType::Gleam);
    }
}